/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpinieRouteImport } from './routes/opinie'
import { Route as ProjektySlugRouteImport } from './routes/projekty.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinieRoute = OpinieRouteImport.update({
  id: '/opinie',
  path: '/opinie',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektySlugRoute = ProjektySlugRouteImport.update({
  id: '/projekty/$slug',
  path: '/projekty/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/opinie': typeof OpinieRoute
  '/projekty/$slug': typeof ProjektySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opinie': typeof OpinieRoute
  '/projekty/$slug': typeof ProjektySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/opinie': typeof OpinieRoute
  '/projekty/$slug': typeof ProjektySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/opinie' | '/projekty/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/opinie' | '/projekty/$slug'
  id: '__root__' | '/' | '/opinie' | '/projekty/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpinieRoute: typeof OpinieRoute
  ProjektySlugRoute: typeof ProjektySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinie': {
      id: '/opinie'
      path: '/opinie'
      fullPath: '/opinie'
      preLoaderRoute: typeof OpinieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekty/$slug': {
      id: '/projekty/$slug'
      path: '/projekty/$slug'
      fullPath: '/projekty/$slug'
      preLoaderRoute: typeof ProjektySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpinieRoute: OpinieRoute,
  ProjektySlugRoute: ProjektySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
